spring:
  application:
    name: mock-api-server

server:
  port: 1234
  servlet:
    context-path: /api/v1

logging:
  pattern:
    console: "%d{yyyy-MM-dd hh:mm:ss a} | %highlight(%level) | [%file:%line] - %msg%n"